name: ship
run-name: Shipping ${{ github.actor }}'s changes
on:
  push:
    branches: [ "main" ]

env:
    REGISTRY: registry.mrtomato.dev
    IMAGE_NAME: mrtomatolegit/daily-polls:latest

jobs:
    ship:
        name: ship image
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install
            - name: Build Application
              run: npm run build
            - name: Login
              run: |
                  echo ${{ secrets.CR_PWD }} | docker login ${{ env.REGISTRY }} -u ${{ secrets.CR_USER }} --password-stdin
            - name: Build and Ship
              run: |
                  docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
